---
name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.12
          - os: ubuntu-20.04
            python-version: 3.6
          - os: macos-latest
            python-version: 3.12
          - os: windows-latest
            python-version: 3.9
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no git@github.com ls || echo ''
          ssh git@github.com || echo ''
          pip install wheel
          pip install -e .[test]

      - name: Authenticate tomial_tooth_collection_api
        run: python -m tomial_tooth_collection_api --authenticate
        env:
          TOMIAL_TOOTH_COLLECTION_TOKEN: ${{ secrets.TOMIAL_TOOTH_COLLECTION_TOKEN }}

      - run: pytest
